- name: Trust CA cert
  hosts: all
  become: yes
  tasks:
    - name: Copy CA
      copy:
        src: "{{ playbook_dir }}/stacks/traefik/config/certs/ca-bundle.crt"
        dest: /etc/pki/ca-trust/source/anchors/STIG-Homelab-ca.crt
    - name: Update trust
      command: update-ca-trust
