# Kanidm Server Configuration
# Ref: https://kanidm.github.io/kanidm/stable/server_configuration.html

bindaddress = "[::]:8443"
ldapbindaddress = "[::]:3636"
db_path = "/data/kanidm.db"
tls_chain = "/data/chain.pem"
tls_key = "/data/key.pem"
domain = "kanidm.${DOMAIN}"
origin = "https://kanidm.${DOMAIN}"
