services:
  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:v1.7.6
    container_name: crowdsec
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - COLLECTIONS=crowdsecurity/linux crowdsecurity/traefik
      # Zero Telemetry / Zero Upload Mandate
      - DISABLE_ONLINE_API=true
      # Prevent sharing with the central API
      - USE_WALTON=false
      # Keep local API enabled for Bouncers and local Vector ingestion
      - DISABLE_LOCAL_API=false
    ports:
      - "8180:8080" # LAPI for bouncers
    volumes:
      - ${DATA_DIR}/crowdsec/config:/etc/crowdsec:z,U
      - ${DATA_DIR}/crowdsec/data:/var/lib/crowdsec/data:z,U
      - /var/log:/var/log:ro # Read host logs
      - ${DATA_DIR}/traefik/logs:/data/traefik-logs:ro,U # Read Traefik access logs
    networks:
      - security-net
      - proxy-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
    healthcheck:
      test: ["CMD", "cscli", "version"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    labels:
      - "security.stig.compliance=true"
      - "security.stig.role=ips"
      - "homepage.group=SOC"
      - "homepage.name=CrowdSec"
      - "homepage.icon=crowdsec.png"
      - "homepage.description=Intrusion Prevention"

networks:
  security-net:
    # Shares network with Falco
    external: true
  proxy-net:
    external: true
