services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.13
    container_name: homepage
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "${PUID:-1000}:${PGID:-1000}"
    userns_mode: keep-id
    ports:
      - 3000:3000
    environment:
      - HOMEPAGE_VAR_DISABLE_UPDATE_CHECK=true
      - HOMEPAGE_OIDC_SECRET=${HOMEPAGE_OIDC_SECRET:-}
      - HOMEPAGE_VAR_WAZUH_URL=https://wazuh.${DOMAIN}
      - HOMEPAGE_VAR_DEFECTDOJO_URL=https://defectdojo.${DOMAIN}
      - HOMEPAGE_VAR_GRAFANA_URL=https://grafana.${DOMAIN}
      - HOMEPAGE_VAR_KANIDM_URL=https://kanidm.${DOMAIN}
      - HOMEPAGE_VAR_QUAY_URL=https://quay.${DOMAIN}
      - HOMEPAGE_VAR_TRAEFIK_URL=https://traefik.${DOMAIN}
      - HOMEPAGE_VAR_TRAEFIK_API=https://traefik.${DOMAIN}
      - HOMEPAGE_VAR_DOCKGE_URL=https://dockge.${DOMAIN}
      - HOMEPAGE_VAR_MINIO_URL=https://minio.${DOMAIN}
      - HOMEPAGE_VAR_MOODLE_URL=https://moodle.${DOMAIN}
      - HOMEPAGE_VAR_N8N_URL=https://n8n.${DOMAIN}
      - HOMEPAGE_VAR_NOTES_URL=https://notes.${DOMAIN}
    volumes:
      - ./config:/app/config:z,U
      - ${PODMAN_SOCK}:/var/run/docker.sock:ro
    networks:
      - mgmt-net
      - proxy-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:3000"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 5m
    labels:
      - "traefik.enable=true"
      - "kanidm.oidc.client_id=homepage"
      - "kanidm.oidc.redirect_path=/api/auth/callback/oidc"
      - "traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.middlewares=oauth2-proxy@file,security-headers@file"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "security.stig.compliance=true"
      - "security.stig.role=dashboard"
      - "homepage.group=Management"
      - "homepage.name=Dashboard"
      - "homepage.icon=homepage.png"
      - "homepage.description=Service Dashboard"
      - "homepage.href=https://${DOMAIN}"

networks:
  mgmt-net:
    external: true
  proxy-net:
    external: true