introspection_addr: :8089
http_listen_addr: :8080
log_level: info
indexer:
  connstring: host=clair-db port=5432 user=${CLAIR_DB_USER} password=${CLAIR_DB_PASSWORD} dbname=${CLAIR_DB_NAME} sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring: host=clair-db port=5432 user=${CLAIR_DB_USER} password=${CLAIR_DB_PASSWORD} dbname=${CLAIR_DB_NAME} sslmode=disable
  max_conn_pool: 100
  migrations: true
notifier:
  connstring: host=clair-db port=5432 user=${CLAIR_DB_USER} password=${CLAIR_DB_PASSWORD} dbname=${CLAIR_DB_NAME} sslmode=disable
  delivery_interval: 1m
  poll_interval: 5m
  migrations: true
metrics:
  prometheus:
    endpoint: /metrics
