apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
  - name: Wazuh (OpenSearch)
    type: grafana-opensearch-datasource
    uid: wazuh-opensearch
    url: http://wazuh-indexer:9200
    access: proxy
    jsonData:
      database: "wazuh-alerts"
      flavor: opensearch
      version: "2.19.4"
      timeField: "@timestamp"
