cluster.name: wazuh-cluster
node.name: wazuh.indexer
network.host: 0.0.0.0
discovery.type: single-node
path.data: /var/lib/opensearch/data

compatibility.override_main_response_version: true
plugins.security.disabled: true
