services:
  traefik:
    image: traefik:v3.3.4
    container_name: traefik
    restart: always
    user: "1000:1000"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/traefik:z
      - ./data/logs:/var/log/traefik:Z
      - ${PODMAN_SOCK}:/var/run/docker.sock:ro
    networks:
      - proxy-net
      - identity-net
      - mgmt-net
      - monitoring-net
      - security-net
      - wazuh-net
      - vulnerability-net
      - harbor-net
      - user-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "security.stig.compliance=true"
      - "security.stig.role=proxy"
      - "homepage.group=Management"
      - "homepage.name=Traefik"
      - "homepage.icon=traefik.png"
      - "homepage.description=Edge Proxy"
      - "homepage.href=https://traefik.${DOMAIN}"

networks:
  proxy-net:
    driver: bridge
    labels:
      - "security.stig.compliance=true"
      - "security.stig.role=proxy-network"
  identity-net:
    external: true
  mgmt-net:
    external: true
  monitoring-net:
    external: true
  security-net:
    external: true
  wazuh-net:
    external: true
  vulnerability-net:
    external: true
  harbor-net:
    external: true
  user-net:
    external: true
