global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vector'
    static_configs:
      - targets: ['vector:9598']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'crowdsec'
    static_configs:
      - targets: ['crowdsec:6060']

  - job_name: 'wazuh-indexer'
    static_configs:
      - targets: ['wazuh-indexer:9200']

  - job_name: 'podman-exporter'
    static_configs:
      - targets: ['podman-exporter:9882']
